const data = [
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: [
      "./assets/images/20220315_142241004.jpg",
      "./assets/images/20220315_142301278.jpg"
    ],
    notes: "Camisa azul con cuadros de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_142455757.jpg"],
    notes: "Camisa azul cielo con rallas de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_142616059.jpg"],
    notes: "Camisa azul cielo con de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga corta hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_142840127.jpg"],
    notes: "Camisa gris de manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga corta hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_142920677.jpg"],
    notes: "Camisa color claro de manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_143008525.jpg"],
    notes: "Camisa azul de manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_143100867.jpg"],
    notes: "Camisa morada de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_143312522.jpg"],
    notes: "Camisa color claro de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga larga hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_143345648.jpg"],
    notes: "Camisa verde de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_143455488.jpg"],
    notes: "Camisa gris de manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa manga corta hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_143531330.jpg"],
    notes: "Camisa cafe de manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Chamarra de trabajo hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "chamarra",
    temporada: "invierno",
    img: ["./assets/images/20220315_143740769.jpg"],
    notes: "Chamarra azul de trabajo para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_143822828.jpg"],
    notes: "Camisa de mezclilla de manga larga para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "xl",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_144128203.jpg"],
    notes: "Camisa de mezclilla beige para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_144824984.jpg"],
    notes: "Camisa azul de cuadros para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camisa para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "otono",
    img: ["./assets/images/20220315_144904040.jpg"],
    notes: "Camisa de pana beige para hombre",
    currentImage: 0,
  },
  {
    tittle: "Camiseta para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "camisa",
    temporada: "verano",
    img: ["./assets/images/20220315_144941516.jpg"],
    notes: "Camiseta azul manga corta para hombre",
    currentImage: 0,
  },
  {
    tittle: "Sueter para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "sueter",
    temporada: "invierno",
    img: ["./assets/images/20220315_145033550.png"],
    notes: "Sueter cafe para hombre",
    currentImage: 0,
  },
  {
    tittle: "Pants corto para hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "pants",
    temporada: "invierno",
    img: ["./assets/images/20220315_145118391.jpg"],
    notes: "Pants corto gris para hombre",
    currentImage: 0,
  },
  {
    tittle: "Calcetines",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "calcetines",
    temporada: "deportivo",
    img: ["./assets/images/20220315_145254950.jpg"],
    notes: "Calcetines amarillos",
    currentImage: 0,
  },
  {
    tittle: "Calcetines",
    price: 30,
    size: "lg",
    condition: "nuevo",
    genero: "hombre",
    tipo: "calcetines",
    temporada: "invierno",
    img: [
      "./assets/images/20220315_145312299.jpg",
      "./assets/images/20220315_145327626.jpg",
    ],
    notes: "Calcetines azul gris",
    currentImage: 0,
  },
  {
    tittle: "Calcetines",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "calcetines",
    temporada: "invierno",
    img: ["./assets/images/20220315_145343022.jpg"],
    notes: "Calcetines cafes",
    currentImage: 0,
  },
  {
    tittle: "Guantes invierno",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "guantes",
    temporada: "invierno",
    img: ["./assets/images/20220315_145358149.jpg"],
    notes: "Guantes cafe para frio",
    currentImage: 0,
  },
  {
    tittle: "Huaraches hombre",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hombre",
    tipo: "calzado",
    temporada: "verano",
    img: [
      "./assets/images/20220315_145803561.jpg",
      "./assets/images/20220315_145725998.jpg",
      "./assets/images/20220315_145750429.jpg",
    ],
    notes: "Huaraches cafe para hombre",
    currentImage: 0,
  },
  {
    tittle: "Botas hombre",
    price: 30,
    size: "lg",
    condition: "Nuevo",
    genero: "hombre",
    tipo: "calzado",
    temporada: "trabajo",
    img: [
      "./assets/images/20220315_145950990.jpg",
      "./assets/images/20220315_145934772.jpg",
      "./assets/images/20220315_150043457.jpg",
    ],
    notes: "Botas de trabajo para hombre",
    currentImage: 0,
  },
  {
    tittle: "Juego de bocinas",
    price: 30,
    size: "lg",
    condition: "usado",
    genero: "hogar",
    tipo: "electronica",
    temporada: "indistinto",
    img: ["./assets/images/20220315_150410117.jpg"],
    notes: "Stereo, juego de bocinas",
    currentImage: 0,
  },
];

export default data;
